apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/restricted/

resources:
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/nginx-ingress/nginx-custom-snippets/disallow-custom-snippets.yaml

patches:
  - path: ./require_labels.yaml
