apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: kyverno-policies-baseline

resources:
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-capabilities/disallow-capabilities.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-host-path/disallow-host-path.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-host-ports-range/disallow-host-ports-range.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-host-ports/disallow-host-ports.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-host-process/disallow-host-process.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-privileged-containers/disallow-privileged-containers.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-proc-mount/disallow-proc-mount.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/disallow-selinux/disallow-selinux.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/restrict-apparmor-profiles/restrict-apparmor-profiles.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/restrict-seccomp/restrict-seccomp.yaml
  - https://raw.githubusercontent.com/kyverno/policies/release-1.8/pod-security/baseline/restrict-sysctls/restrict-sysctls.yaml
