apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: kyverno-policies-enforce

components:
 - ../restricted/

patches:
  - patch: |-
      - op: replace
        path: /spec/validationFailureAction
        value: enforce
    target:
      kind: ClusterPolicy

