apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: kyverno
spec:
  project: default
  source:
    repoURL: https://github.com/JuanPabloSGU/argocd-Kyverno.git
    targetRevision: HEAD
    path: ./base/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
