apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jqPathExpressions:
        - .spec.rules[] | 
          select(.name|test("autogen-."))
  project: default
  source:
    repoURL: https://github.com/JuanPabloSGU/argocd-Kyverno.git
    targetRevision: HEAD
    path: k8s/kyverno-policies/overlays/restricted
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - respectIgnoreDifferences=true
