apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/JuanPabloSGU/argocd-Kyverno.git
    path: k8s/kyverno-policies/
    targetRevision: HEAD
    helm:
      valueFiles:
        - sandbox/values.yaml
  project: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - respectIgnoreDifferences=true
      - ApplyOutofSyncOnly=true
